### PR TITLE
Added RLN8-410-E to the UART table

### PR DESCRIPTION
**Pull request by ternium1**
Hello, I'm trying to explore this project and adapt it to my NVR which is an RLN8-410-E (hardware model is H3MB16), I do have access to the UART console, that's why I added it to the UART table on the README.md

### CODE REVIEW

**Comment by goncalomb** [comment]
Hi. Thanks. It's good to have someone else test this on other hardware versions. The project is a bit abandoned but I do want to return to it in the near future. Let me know if you can compile/run the binaries on your device.

**Comment by ternium1** [comment]
Hello,
For now, I've tried 4 different test cases to check if `autoexec.sh` executed but none of them worked:
* USB alone on front port
* USB alone on back port
* USB front + mouse back
* USB back + mouse front
I've tried 3 different USB sticks (USB 2 & 3 from 16GB to 32GB)
I'm going to try 2 USBs to check...

I've also tried to run the build script but there are some errors during the nmap compilation (missing imports), I'm going to try on a different machine later and let you know

**Comment by goncalomb** [comment]
The USB `autoexec.sh` can be quite finicky, I had one old Toshiba USB 2.0 stick that worked repeatedly, but it died after a while (I don't think it was related, it was just a old USB stick). I have some other USB sticks that I bought last year specifically to test this, I think 2 of those didn't work, I still have to test the rest. The system just waits 1 or 2 seconds for `/dev/usb/usbhd1` to be available and sometimes that is not enough for the drive to be detected by the kernel. You can see on the serial log (UART) if it detected the drive fast enough.

In relation to the build, it is probably broken because of changes to the dependencies (this case nmap). Most likely is not your system, because the build runs inside a fixed Docker container and that is stable. I should change it to use git submodules instead of fetching the latest code every time, that way we can lock in a specific version.

**Comment by goncalomb** [comment]
I made some changes (see de0070b), you should now be able to build the binaries, I've locked to nmap to a older version that compiles correctly (should be bumped later). It's using git submodules now for the dependencies, so you need to run `git submodule update --init` on your local repo or `git clone --recursive ...` before running `./nvr-unleashed/build.sh`.

**Comment by ternium1** [comment]
Hi back,
I successfully managed to build the binaries :)
However, I had to edit the UNLEASHED_LOCATION to `/mnt/tmp` instead of `/tmp` due to Read-only fs error (I don't know if this is due to the v2.x firmware version, and this specific NVR doesn't support v3 so I cannot test).
I've tested a command to extract the NVR version (`grep board_name dvr.xml | awk -F= '{print $2}'`, I'll try to automate the autoexec.sh to mount to /mnt/tmp instead of /tmp. ~Also it appears my NVR doesn't have the config.gz~ (I had to run the autoexec twice)
Appraently running the autoexec the second time caused a kernel panic because it ran out of memory (`Kernel panic - not syncing: Out of memory: system-wide panic_on_oom is enabled`)

**Comment by ternium1** [comment]
Do you have a sample of the config.gz file so I can see if there are any traces of a similar file on my NVR fs?

**Comment by goncalomb** [comment]
The `/mnt/tmp/` also works on my version (it's also a tmpfs mount), so that's fine. We can just change that.

---

The out of memory issue is probably related to the fact that I'm copying the bin files to the temporary directory (tmpfs mount, memory backed). I should probably change that to not actually copy the binaries, just use symbolic links. For now you can just not include all the binaries on the stick, `nmap` is quite big.

---

The file `config.gz` is available at `/proc/config.gz` (just a text file, gzipped, that contains all the kernel configurations used to build the kernel). Iit's only available if the kernel was compiled with IKCONFIG + IKCONFIG_PROC.

https://wiki.gentoo.org/wiki/Kernel/IKCONFIG_support

I've been doing some research, I'm by no means an expert on kernel stuff, but I've been inspecting some firmware versions and:

* `v3.0.0.110_20122648` (my version, never updated) kernel version `4.9.44` YES IKCONFIG + IKCONFIG_PROC
* `v3.2.0.214_22120248` (downloaded from reolink) kernel version `4.9.44` YES IKCONFIG + IKCONFIG_PROC
* `v2.0.0.280_21060101` (downloaded from reolink) kernel version `3.18.20` NO IKCONFIG
* `v2.0.0.280_21060101` (older version from reolink-fw-archive) kernel version `3.18.20` NO IKCONFIG

So version 2 are using kernel builds that don't include IKCONFIG so the config is not available.

If you want to try to build the kernel modules for your kernel version (check with `uname -r`, it's probably `3.18.20`), you should change the version on `./nvr-unleashed/env-modules/build.sh`. I've not tested this. You can try with my `config.gz` (it's the same used on the latest v3 firmware) but because it's for the kernel 4.9.44 it might not work...

My [config.gz](https://github.com/goncalomb/reolink-tools/files/10465465/config.gz) from `v3.0.0.110_20122648`.

**Comment by goncalomb** [comment]
I tested `/mnt/tmp/` also works on my version, so that's fine. We can just change that.

---

The out of memory issue is probably related to the fact that I'm copying the bin files to the tmp directory (that is a tmpfs, memory backed), I should probably change that to not actually copy the binaries, just use symbolic links. For now you can just not include all the binaries on the stick, `nmap` is quite big.

---

The kernel IKCONFIG config controls if the kernel is compiled with embedded config file.

https://wiki.gentoo.org/wiki/Kernel/IKCONFIG_support

The file `config.gz` is available at `/proc/config.gz` if the kernel was compiled with IKCONFIG_PROC.

I've been doing some research, I'm by no means an expert on kernel stuff, but I've been unpacking some firmware files and:

* `v3.0.0.110_20122648` (my version, never updated) kernel version `4.9.44` YES IKCONFIG + IKCONFIG_PROC
* `v3.2.0.214_22120248` (downloaded from reolink) kernel version `4.9.44` YES IKCONFIG + IKCONFIG_PROC
* `v2.0.0.280_21060101` (downloaded from reolink) kernel version `3.18.20` NO IKCONFIG
* `v2.0.0.269_20042901` (older version from reolink-fw-archive) kernel version `3.18.20` NO IKCONFIG

So version 2 are using kernel builds that don't include IKCONFIG so the config is not available.

---

If you want to try to build the kernel modules for your kernel version (check with `uname -r` it's probably `3.18.20`), you should change the version on `./nvr-unleashed/env-modules/build.sh`. I've not tested this. You can try with my `config.gz` (it's the same used on the latest v3 firmware) but because it's for the kernel 4.9.44 it probably won't work...

**Pull request merged**
